# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-08-19 21:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='end_year',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='job',
            name='start_year',
            field=models.DateField(),
        ),
    ]
