# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-08-19 21:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20170819_2134'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='end_year',
            field=models.DateField(blank=True, null=True),
        ),
    ]
