# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-22 04:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20170820_0048'),
    ]

    operations = [
        migrations.CreateModel(
            name='Interest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=55)),
                ('keywords', models.CharField(max_length=15)),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.AddField(
            model_name='job',
            name='synopsis',
            field=models.TextField(default='TBD'),
            preserve_default=False,
        ),
    ]
